version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
  db:
     image: postgres:latest
     environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
     volumes:
      - pgdata:/var/lib/postgresql/data

  
volumes:
  pgdata:
